In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/raw/car_prices.csv',sep=',')

In [5]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
car_ID,205.0,103.000000,59.322565,1.00,52.00,103.00,154.00,205.00
symboling,205.0,0.834146,1.245307,-2.00,0.00,1.00,2.00,3.00
CarName,205.0,77.209756,41.014583,0.00,44.00,80.00,115.00,146.00
fueltype,205.0,0.902439,0.297446,0.00,1.00,1.00,1.00,1.00
aspiration,205.0,0.180488,0.385535,0.00,0.00,0.00,0.00,1.00
doornumber,205.0,0.439024,0.497483,0.00,0.00,0.00,1.00,1.00
carbody,205.0,2.614634,0.859081,0.00,2.00,3.00,3.00,4.00
drivewheel,205.0,1.326829,0.556171,0.00,1.00,1.00,2.00,2.00
enginelocation,205.0,0.014634,0.120377,0.00,0.00,0.00,0.00,1.00
wheelbase,205.0,98.756585,6.021776,86.60,94.50,97.00,102.40,120.90
carlength,205.0,174.049268,12.337289,141.10,166.30,173.20,183.10,208.10
carwidth,205.0,65.907805,2.145204,60.30,64.10,65.50,66.90,72.30
carheight,205.0,53.724878,2.443522,47.80,52.00,54.10,55.50,59.80
curbweight,205.0,2555.565854,520.680204,1488.00,2145.00,2414.00,2935.00,4066.00
enginetype,205.0,3.014634,1.054765,0.00,3.00,3.00,3.00,6.00
cylindernumber,205.0,2.117073,0.795792,0.00,2.00,2.00,2.00,6.00
enginesize,205.0,126.907317,41.642693,61.00,97.00,120.00,141.00,326.00
fuelsystem,205.0,3.253659,2.013204,0.00,1.00,5.00,5.00,7.00
boreratio,205.0,3.329756,0.270844,2.54,3.15,3.31,3.58,3.94
stroke,205.0,3.255415,0.313597,2.07,3.11,3.29,3.41,4.17
compressionratio,205.0,10.142537,3.972040,7.00,8.60,9.00,9.40,23.00
horsepower,205.0,104.117073,39.544167,48.00,70.00,95.00,116.00,288.00
peakrpm,205.0,5125.121951,476.985643,4150.00,4800.00,5200.00,5500.00,6600.00
citympg,205.0,25.219512,6.542142,13.00,19.00,24.00,30.00,49.00
highwaympg,205.0,30.751220,6.886443,16.00,25.00,30.00,34.00,54.00
price,205.0,13276.710571,7988.852332,5118.00,7788.00,10295.00,16503.00,45400.00

In [12]:
overview = df.describe()

In [16]:
overview.loc[["min","max"]].to_json("../prediction_service/schema_in.json")